name: CI

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '16'
      - name: build with maven
        run: mvn -s settings.xml -B package
        env:
          GHPKG_TOKEN: ${{ secrets.GHPKG_TOKEN }}
      - name: upload build artefact
        uses: actions/upload-artifact@v2
        with:
          name: app.jar
          path: target/mvn-consumer-1.0.jar
